version: "3"

services:
  apache:
    build:
      context: .docker
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION-8.2}
        GID: ${LOCAL_GROUP_ID-1000}
        UID: ${LOCAL_USER_ID-1000}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION-apache}"
    ports:
      - "${HTTP_PORT-80}:80"
    volumes:
      - ${DOCUMENT_ROOT-./app}:/var/www/html:rw
      - ${PHP_INI-./.docker/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./.docker/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./.docker/log/apache2}:/var/log/apache2
      - ${XDEBUG_LOG_DIR-./.docker/log/xdebug}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT-9003}"
      XDEBUG_MODE: off
    extra_hosts:
      - "host.docker.internal:host-gateway"
